---
- hosts: 172.16.102.192
  become: true
  tasks:
  - name: Check les mdp root & allouer les droits replication
    community.mysql.mysql_user:
    name: root
    host: "{{ item }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    password: "{{ mysql.root_db_password }}"
    priv: '*.*:REPLICATION SLAVE,GRANT'
    check_implicit_admin: true
    loop: "{{ mysql.hosts }}"
    become: yes
    notify: "restart mysql"
    with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

  - name: Create `/root/.my.cnf`  with root password credentials
    template:
     src:  my.cnf.j2
     dest: /root/.my.cnf
     owner: root
     mode: 0600
    notify: "restart mysql"

  handlers:
   - name: Restart mysql
     ansible.builtin.service:
      name: mysql
      state: restarted
     listen: "restart mysql"