---
- hosts: master
  become: true
  vars:
    mysql:
        - hosts: 127.0.0.1
        - root_db_password: root
  tasks:
      - name: Add root user 
        community.mysql.mysql_user:
         name: root
         host: 127.0.0.1
         login_unix_socket: /var/run/mysqld/mysqld.sock
         password: root
         priv: "*.*:ALL"
         check_implicit_admin: true
         state: present
        loop: "{{ mysql }}"
        become: yes
        notify: "restart mysql"

      - name: Create `/root/.my.cnf` with root password credentials
        template:
         src:  my.cnf.j2
         dest: /root/.my.cnf
         owner: root
         mode: 0600
        notify: "restart mysql"
       
      - name: Correct root user parameters
        become: yes
        command: mysql --execute "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root';"
       
      - name: Create user with replication rights
        become: yes
        community.mysql.mysql_user:
         name: olivier
         password: "12345"
         priv: "*.*:ALL"
         state: present

        
  handlers:
   - name: Restart mysql
     ansible.builtin.service:
      name: mysql
      state: restarted
     listen: "restart mysql"