all:
    children:
        syslog:
           hosts:
                srv-syslog:
                    ansible_ssh_user: sfleury
        web:
            hosts:
                web1:
                    ansible_ssh_user: sfleury
                web2:
                    ansible_ssh_user: sfleury
        bdd:
            hosts:
                bddmaster:
                    ansible_ssh_user: sfleury
                bddslave:
                    ansible_ssh_user: sfleury
