all:
    children:
        syslog:
           hosts:
                srv-syslog:
                    ansible_ssh_user: ansible
        web:
            hosts:
                web01.com:
                    ansible_ssh_user: ansible
                web02.com:
                    ansible_ssh_user: ansible
        bdd:
            hosts:
                bddmaster:
                    ansible_ssh_user: ansible
                bddslave:
                    ansible_ssh_user: ansible