all:
 databases:
  master:
   hosts:
    172.16.102.192:
     ansible_ssh_user: olivier
     replica_id: 1
  slave: 
   hosts:
    172.16.102.194:
     ansible_ssh_user: olivier
     replica_id: 2