---
- hosts: 172.16.102.192
  become: true
  vars:
   source: "mastermysqld.conf"
  tasks:
  - name: Vérifier l'existence de mysqld.cnf
    ansible.builtin.stat:
     path: "/etc/mysql/mysql.conf.d/mysqld.cnf"
    register: mysqld
  - name: Si existe, backup
    command: mv /etc/mysql/mysql.conf.d/mysqld.cnf /etc/mysql/mysql.conf.d/mysqld.cnf.old
    when: mysqld.stat.exists
  - name: Copie de la conf
    ansible.builtin.copy:
     remote_src: false
     src: "mastermysqld.conf"
     dest: "/etc/mysql/mysql.conf.d/mysqld.cnf"
  - name: Redémarrer le service
    systemd:
     name: mysql
     state: restarted
     enabled: yes