- hosts: all
  become: yes
  tasks:
   - name: Création utilisateur ansible
     user:
       name: ansible 
       groups:
        - sudo
       state: present
       shell: /bin/bash       
       system: no             
       createhome: yes       
       home: /home/ansible
   - name: Pas de mot de passe SUDO
     template:
       src: ansible.j2
       dest: /etc/sudoers.d/ansible
       owner: root
       group: root
   - name: Transfert clé publique SSH
     authorized_key:
        user: ansible
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}" 


---

- name: ajout user
  hosts: web
  gather_facts: false
  vars_files:
    - Vault/password.yml
    - WordPress_LAMP/vars/user_vars.yml

  tasks:
    - name: Ajout user apache avec password Vault
      ansible.builtin.user:
        name: "{{item.username}}"
        password: "{{item.password}}"
        comment: "{{item.username}}"
        home: "{{item.home}}"
        update_password : on_create
      with_items:
        - "{{client}}"