- hosts: all
  become: yes
  tasks:
   - name: Création utilisateur ansible
     user:
       name: ansible 
       groups:
        - sudo
       state: present
       shell: /bin/bash       
       system: no             
       createhome: yes       
       home: /home/ansible
   - name: Pas de mot de passe SUDO
     template:
       src: ansible.j2
       dest: /etc/sudoers.d/ansible
       owner: root
       group: root
   - name: Transfert clé publique SSH
     authorized_key:
        user: ansible
        state: present
        key: "{{ lookup('file', 'ssh/ssh_keys_admin.j2') }}"
   - name: Installation RSyslog
     apt:
      name: rsyslog
      state: present
   - name: Démarrage service RSyslog si non démarré
     ansible.builtin.service:
      name: rsyslog
      state: started
   - name: Activation service RSyslog au démarrage du système
     ansible.builtin.service:
      name: rsyslog
      enabled: yes  
   - name: Configuration RSyslog
     template:
       src: templates/syslogconfclient.j2
       dest: /etc/rsyslog.conf
     notify: restart rsyslog
   - name: Build hosts file
     lineinfile:
      dest: /etc/hosts
      regexp: '.*{{ item }}$'
      line: '{{ hostvars[item].ansible_default_ipv4.address }} {{item}}'
      state: present
     with_items: '{{ groups["all"] }}'