- name: ajout user
  hosts: web
  gather_facts: false
  vars_files:
    - password.yml
  vars:
    client:
      - username: client1
        domain: client1.com
        password: "{{client1}}"
        home: /var/www/client1.com
      
      - username: client2
        domain: client2.com
        password: "{{client2}}"
        home: /var/www/client2.com

      - username: client3
        domain: client3.com
        password: "{{client3}}"
        home: /var/www/client3.com

  tasks:
    - name: Ajout user apache avec password Vault
      ansible.builtin.user:
        name: "{{item.username}}"
        password: "{{item.password}}"
        comment: "{{item.username}}"
        home: "{{item.home}}"
        update_password : on_create
      with_items:
        - "{{client}}"