---
#System Settings
php_modules: [ 'php-curl', 'php-gd', 'php-mbstring', 'php-xml', 'php-xmlrpc', 'php-soap', 'php-intl', 'php-zip' ]

#MySQL Settings
mysql_root_password: "axel"
mysql_db: "wordpress"
mysql_user: "axel"
mysql_password: "axel"

#HTTP Settings
http_host: "ansible-wp"
http_conf: "ansible-wp.conf"
http_port: "80"