- hosts: web
  become: yes
  tasks:

   - name: Add User ansible for SSH
     user:
       name: ansible 
       groups:
        - sudo
       state: present
       shell: /bin/bash       
       system: no             
       createhome: yes       
       home: /home/ansible

   - name: Pas de mot de passe SUDO
     template:
       src: ansible.j2
       dest: /etc/sudoers.d/ansible
       owner: root
       group: root

   - name: Transfert clé publique SSH
     authorized_key:
        user: ansible
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
